export const GET_PROPERTY = 'GET_PROPERTY'
export const POST_PROPERTY = 'POST_PROPERTY'
export const GET_CATEGORYS = 'GET_CATEGORYS'
export const FILTER_CATEGORY = 'FILTER_CATEGORY'
export const FILTER_LOCATION = 'FILTER_LOCATION'
export const GET_LOCATIONS = 'GET_LOCATIONS'
export const GET_DETAIL = "GET_DETAIL";
export const CREATE_USER = "CREATE_USER"